server:
  port: 8081

name: 测试名
# @ConfigurationProperties(prefix = "hello")
# helloControllerId
hello:
  hello-controller-id: 1001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
